// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"
	"time"
)

const findRefreshToken = `-- name: FindRefreshToken :one
SELECT id, customer_id, role, token_hash, expires_at, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) FindRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidRefreshToken = `-- name: InvalidRefreshToken :exec
UPDATE refresh_tokens 
SET expires_at = NOW() 
WHERE token_hash = $1
`

func (q *Queries) InvalidRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, invalidRefreshToken, tokenHash)
	return err
}

const saveRefreshToken = `-- name: SaveRefreshToken :one
INSERT INTO refresh_tokens (customer_id, role, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, NOW()) RETURNING id, customer_id, role, token_hash, expires_at, created_at
`

type SaveRefreshTokenParams struct {
	CustomerID string    `json:"customer_id"`
	Role       string    `json:"role"`
	TokenHash  string    `json:"token_hash"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, saveRefreshToken,
		arg.CustomerID,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
