// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"
	"time"
)

const saveRefreshToken = `-- name: SaveRefreshToken :one
INSERT INTO refresh_tokens (customer_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, NOW()) RETURNING id, customer_id, token_hash, expires_at, created_at
`

type SaveRefreshTokenParams struct {
	CustomerID string    `json:"customer_id"`
	TokenHash  string    `json:"token_hash"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, saveRefreshToken, arg.CustomerID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
