// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, email, phone, password, birthdate, role, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW()) RETURNING id, name, email, phone, password, birthdate, role, created_at, updated_at, deleted_at
`

type CreateCustomerParams struct {
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Phone     string      `json:"phone"`
	Password  string      `json:"password"`
	Birthdate pgtype.Date `json:"birthdate"`
	Role      string      `json:"role"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Birthdate,
		arg.Role,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Birthdate,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findCustomerByEmail = `-- name: FindCustomerByEmail :one
SELECT id, name, email, phone, password, birthdate, role, created_at, updated_at, deleted_at FROM customers WHERE email = $1
`

func (q *Queries) FindCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRow(ctx, findCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Birthdate,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findCustomerByID = `-- name: FindCustomerByID :one
SELECT id, name, email, phone, password, birthdate, role, created_at, updated_at, deleted_at FROM customers WHERE id = $1
`

func (q *Queries) FindCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, findCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Birthdate,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const loadCustomers = `-- name: LoadCustomers :many
SELECT id, name, email, phone, password, birthdate, role, created_at, updated_at, deleted_at FROM customers
`

func (q *Queries) LoadCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, loadCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Password,
			&i.Birthdate,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :exec
UPDATE customers SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteCustomer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCustomer, id)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers 
SET name = $2, email = $3, phone = $4, birthdate = $5, role = $6, updated_at = NOW() 
WHERE id = $1
`

type UpdateCustomerParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Phone     string      `json:"phone"`
	Birthdate pgtype.Date `json:"birthdate"`
	Role      string      `json:"role"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.Exec(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Birthdate,
		arg.Role,
	)
	return err
}
