// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, email, phone, password, birthdate, created_at)
VALUES ($1, $2, $3, $4, $5, NOW()) RETURNING id, name, email, phone, password, birthdate, created_at, updated_at, deleted_at
`

type CreateCustomerParams struct {
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Phone     string      `json:"phone"`
	Password  string      `json:"password"`
	Birthdate pgtype.Date `json:"birthdate"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Birthdate,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Birthdate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findCustomerByID = `-- name: FindCustomerByID :one
SELECT id, name, email, phone, password, birthdate, created_at, updated_at, deleted_at FROM customers WHERE id = $1
`

func (q *Queries) FindCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, findCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Birthdate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const loadCustomers = `-- name: LoadCustomers :many
SELECT id, name, email, phone, password, birthdate, created_at, updated_at, deleted_at FROM customers
`

func (q *Queries) LoadCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, loadCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Password,
			&i.Birthdate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
