// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enterprise.sql

package database

import (
	"context"
	"time"
)

const registerEnterprise = `-- name: RegisterEnterprise :one
INSERT INTO enterprise (trade_name, cnpj, opening_time, closing_time, updated_at) 
VALUES ($1, $2, $3, $4, NULL) RETURNING id, trade_name, cnpj, opening_time, closing_time, created_at, updated_at
`

type RegisterEnterpriseParams struct {
	TradeName   string    `json:"trade_name"`
	Cnpj        string    `json:"cnpj"`
	OpeningTime time.Time `json:"opening_time"`
	ClosingTime time.Time `json:"closing_time"`
}

func (q *Queries) RegisterEnterprise(ctx context.Context, arg RegisterEnterpriseParams) (Enterprise, error) {
	row := q.db.QueryRow(ctx, registerEnterprise,
		arg.TradeName,
		arg.Cnpj,
		arg.OpeningTime,
		arg.ClosingTime,
	)
	var i Enterprise
	err := row.Scan(
		&i.ID,
		&i.TradeName,
		&i.Cnpj,
		&i.OpeningTime,
		&i.ClosingTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
