// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: procedure.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProcedure = `-- name: CreateProcedure :one
INSERT INTO procedures (registred_by, name, description, banner_url, price, duration_minutes, available, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, registred_by, name, description, banner_url, price, duration_minutes, available, created_at, updated_at
`

type CreateProcedureParams struct {
	RegistredBy     pgtype.UUID `json:"registred_by"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	BannerUrl       pgtype.Text `json:"banner_url"`
	Price           float64     `json:"price"`
	DurationMinutes int32       `json:"duration_minutes"`
	Available       bool        `json:"available"`
	UpdatedAt       *time.Time  `json:"updated_at"`
}

func (q *Queries) CreateProcedure(ctx context.Context, arg CreateProcedureParams) (Procedure, error) {
	row := q.db.QueryRow(ctx, createProcedure,
		arg.RegistredBy,
		arg.Name,
		arg.Description,
		arg.BannerUrl,
		arg.Price,
		arg.DurationMinutes,
		arg.Available,
		arg.UpdatedAt,
	)
	var i Procedure
	err := row.Scan(
		&i.ID,
		&i.RegistredBy,
		&i.Name,
		&i.Description,
		&i.BannerUrl,
		&i.Price,
		&i.DurationMinutes,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProcedureByID = `-- name: FindProcedureByID :one
SELECT id, registred_by, name, description, banner_url, price, duration_minutes, available, created_at, updated_at FROM procedures WHERE id = $1
`

func (q *Queries) FindProcedureByID(ctx context.Context, id pgtype.UUID) (Procedure, error) {
	row := q.db.QueryRow(ctx, findProcedureByID, id)
	var i Procedure
	err := row.Scan(
		&i.ID,
		&i.RegistredBy,
		&i.Name,
		&i.Description,
		&i.BannerUrl,
		&i.Price,
		&i.DurationMinutes,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
