// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	LoadCustomers(ctx context.Context) ([]Customer, error)
}

var _ Querier = (*Queries)(nil)
