// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateProcedure(ctx context.Context, arg CreateProcedureParams) (Procedure, error)
	FindCustomerByEmail(ctx context.Context, email string) (Customer, error)
	FindCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error)
	FindProcedureByID(ctx context.Context, id pgtype.UUID) (Procedure, error)
	FindRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	InvalidRefreshToken(ctx context.Context, tokenHash string) error
	LoadCustomers(ctx context.Context) ([]Customer, error)
	RegisterEnterprise(ctx context.Context, arg RegisterEnterpriseParams) (Enterprise, error)
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error)
	SoftDeleteCustomer(ctx context.Context, id pgtype.UUID) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error
}

var _ Querier = (*Queries)(nil)
