// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	FindCustomerByEmail(ctx context.Context, email string) (Customer, error)
	FindCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error)
	LoadCustomers(ctx context.Context) ([]Customer, error)
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error)
	SoftDeleteCustomer(ctx context.Context, id pgtype.UUID) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error
}

var _ Querier = (*Queries)(nil)
