name: Deploy to NebrinnoLab

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Go Configure
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.4'

      - name: Binary Compile
        run: |
          make build

      - name: Copy artifacts to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "bs-aesthetics-api,database/,Makefile,sqlc.yaml,docker-compose.yml"
          target: "/home/brunosilv/bs-aesthetics/api"
          strip_components: 0

      - name: Restart Service on VPS
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/brunosilv/bs-aesthetics/api
            chmod +x bs-aesthetics-api
            make setup
            sudo systemctl restart bs-aesthetics.service
            sudo systemctl status bs-aesthetics.service --no-pager